/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FormAPP;

/**
 *
 * @author Tony's PC
 */
public class PopupDataLogin extends javax.swing.JFrame {

    /**
     * Creates new form PopupDataLogin
     */
    public PopupDataLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PopupDataLogin = new javax.swing.JPanel();
        lbl_Menu6 = new javax.swing.JLabel();
        lbl_Menu16 = new javax.swing.JLabel();
        lbl_judul9 = new javax.swing.JLabel();
        lbl_idbooking = new javax.swing.JLabel();
        lbl_idbooking1 = new javax.swing.JLabel();
        lbl_idbooking2 = new javax.swing.JLabel();
        txtBooking2 = new javax.swing.JTextField();
        txtBooking3 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        Daftar = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(580, 340));
        setPreferredSize(new java.awt.Dimension(580, 340));
        getContentPane().setLayout(null);

        PopupDataLogin.setBackground(new java.awt.Color(255, 255, 255));
        PopupDataLogin.setInheritsPopupMenu(true);
        PopupDataLogin.setMinimumSize(new java.awt.Dimension(580, 340));
        PopupDataLogin.setPreferredSize(new java.awt.Dimension(580, 340));
        PopupDataLogin.setLayout(null);

        lbl_Menu6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_Menu6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_Menu6MouseClicked(evt);
            }
        });
        PopupDataLogin.add(lbl_Menu6);
        lbl_Menu6.setBounds(10, 10, 0, 0);

        lbl_Menu16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_Menu16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_Menu16MouseClicked(evt);
            }
        });
        PopupDataLogin.add(lbl_Menu16);
        lbl_Menu16.setBounds(10, 10, 0, 0);

        lbl_judul9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SI_AiraKost_Asset/Label1.png"))); // NOI18N
        PopupDataLogin.add(lbl_judul9);
        lbl_judul9.setBounds(200, 0, 200, 60);

        lbl_idbooking.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbl_idbooking.setText("Hak Akses");
        PopupDataLogin.add(lbl_idbooking);
        lbl_idbooking.setBounds(90, 230, 76, 22);

        lbl_idbooking1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbl_idbooking1.setText("Username");
        PopupDataLogin.add(lbl_idbooking1);
        lbl_idbooking1.setBounds(90, 130, 71, 22);

        lbl_idbooking2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbl_idbooking2.setText("Password");
        PopupDataLogin.add(lbl_idbooking2);
        lbl_idbooking2.setBounds(90, 180, 76, 22);

        txtBooking2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        PopupDataLogin.add(txtBooking2);
        txtBooking2.setBounds(200, 130, 250, 28);

        txtBooking3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        PopupDataLogin.add(txtBooking3);
        txtBooking3.setBounds(200, 180, 250, 28);

        jComboBox2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Hak Akses", "Admin", "User" }));
        PopupDataLogin.add(jComboBox2);
        jComboBox2.setBounds(200, 230, 250, 30);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(140, 120, 120));
        jLabel1.setText("Data Login");
        PopupDataLogin.add(jLabel1);
        jLabel1.setBounds(250, 70, 100, 30);

        Daftar.setBackground(new java.awt.Color(52, 135, 239));
        Daftar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Daftar.setForeground(new java.awt.Color(255, 255, 255));
        Daftar.setText("Daftar");
        Daftar.setBorder(null);
        Daftar.setBorderPainted(false);
        Daftar.setContentAreaFilled(false);
        Daftar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Daftar.setOpaque(true);
        Daftar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DaftarActionPerformed(evt);
            }
        });
        PopupDataLogin.add(Daftar);
        Daftar.setBounds(260, 280, 90, 30);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        PopupDataLogin.add(jScrollPane1);
        jScrollPane1.setBounds(10, 330, 570, 106);

        getContentPane().add(PopupDataLogin);
        PopupDataLogin.setBounds(0, 0, 590, 450);

        setSize(new java.awt.Dimension(606, 488));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_Menu6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_Menu6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_Menu6MouseClicked

    private void lbl_Menu16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_Menu16MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_Menu16MouseClicked

    private void DaftarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DaftarActionPerformed

    }//GEN-LAST:event_DaftarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PopupDataLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PopupDataLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PopupDataLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PopupDataLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PopupDataLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton Daftar;
    private javax.swing.JPanel PopupDataLogin;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbl_Menu16;
    private javax.swing.JLabel lbl_Menu6;
    private javax.swing.JLabel lbl_idbooking;
    private javax.swing.JLabel lbl_idbooking1;
    private javax.swing.JLabel lbl_idbooking2;
    private javax.swing.JLabel lbl_judul9;
    private javax.swing.JTextField txtBooking2;
    private javax.swing.JTextField txtBooking3;
    // End of variables declaration//GEN-END:variables
}
