/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FormAPP;

import java.awt.Image;
import java.awt.Toolkit;
import java.util.TimerTask;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Tony's PC
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Menu() {
        initComponents();
        ScrollData.getVerticalScrollBar().setUnitIncrement(8);
        iconApp();
    }

    private void iconApp() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/SI_AiraKost_Asset/ico2.png")));
    }

    private void setColorText(JLabel label) {
        label.setForeground(new java.awt.Color(255, 255, 255));
    }

    private void resetColorText(JLabel label) {
        label.setForeground(new java.awt.Color(207, 207, 207));
    }

    private void setColor(JPanel panel) {
        panel.setBackground(new java.awt.Color(96, 82, 76));
    }

    private void resetColor(JPanel panel) {
        panel.setBackground(new java.awt.Color(140, 120, 111));
    }

    int xy, xx;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Bg = new javax.swing.JPanel();
        BerandaSideBar = new javax.swing.JPanel();
        Menu1 = new javax.swing.JLabel();
        minimized2 = new javax.swing.JButton();
        minimized3 = new javax.swing.JButton();
        close1 = new javax.swing.JButton();
        judul1 = new javax.swing.JLabel();
        Slide1 = new javax.swing.JLabel();
        Text2 = new javax.swing.JLabel();
        previous1 = new javax.swing.JLabel();
        next1 = new javax.swing.JLabel();
        Kamar3 = new javax.swing.JLabel();
        CekButton3 = new javax.swing.JButton();
        CekButton4 = new javax.swing.JButton();
        Kamar4 = new javax.swing.JLabel();
        KamarSideBar = new javax.swing.JPanel();
        Menu2 = new javax.swing.JLabel();
        minimized4 = new javax.swing.JButton();
        minimized5 = new javax.swing.JButton();
        close2 = new javax.swing.JButton();
        judul2 = new javax.swing.JLabel();
        CekButton5 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        PemesananSideBar = new javax.swing.JPanel();
        Menu5 = new javax.swing.JLabel();
        minimized8 = new javax.swing.JButton();
        minimized9 = new javax.swing.JButton();
        close4 = new javax.swing.JButton();
        judul4 = new javax.swing.JLabel();
        CekButton6 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        ScrollData = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        Masuk = new javax.swing.JToggleButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jLabel49 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        SideBarMenu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        beranda = new javax.swing.JPanel();
        ico_beranda = new javax.swing.JLabel();
        Lbl_beranda = new javax.swing.JLabel();
        kamar = new javax.swing.JPanel();
        ico_kamar = new javax.swing.JLabel();
        Lbl_kamar = new javax.swing.JLabel();
        pemesanan = new javax.swing.JPanel();
        ico_pemesanan = new javax.swing.JLabel();
        Lbl_pemesanan = new javax.swing.JLabel();
        Logout = new javax.swing.JToggleButton();
        BerandaNoSidebar = new javax.swing.JPanel();
        Menu3 = new javax.swing.JLabel();
        minimized1 = new javax.swing.JButton();
        minimized = new javax.swing.JButton();
        close = new javax.swing.JButton();
        judul = new javax.swing.JLabel();
        next = new javax.swing.JLabel();
        previous = new javax.swing.JLabel();
        Slide = new javax.swing.JLabel();
        Text1 = new javax.swing.JLabel();
        CekButton2 = new javax.swing.JButton();
        Kamar2 = new javax.swing.JLabel();
        CekButton1 = new javax.swing.JButton();
        Kamar1 = new javax.swing.JLabel();
        KamarNoSidebar = new javax.swing.JPanel();
        Menu4 = new javax.swing.JLabel();
        minimized6 = new javax.swing.JButton();
        minimized7 = new javax.swing.JButton();
        close3 = new javax.swing.JButton();
        judul3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        PemesananNoSidebar = new javax.swing.JPanel();
        Menu6 = new javax.swing.JLabel();
        minimized10 = new javax.swing.JButton();
        minimized11 = new javax.swing.JButton();
        close5 = new javax.swing.JButton();
        judul5 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel50 = new javax.swing.JLabel();
        ScrollData1 = new javax.swing.JScrollPane();
        jPanel8 = new javax.swing.JPanel();
        Masuk1 = new javax.swing.JToggleButton();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jLabel55 = new javax.swing.JLabel();
        jTextField16 = new javax.swing.JTextField();
        jLabel56 = new javax.swing.JLabel();
        jTextField17 = new javax.swing.JTextField();
        jLabel57 = new javax.swing.JLabel();
        jTextField18 = new javax.swing.JTextField();
        jLabel58 = new javax.swing.JLabel();
        jTextField19 = new javax.swing.JTextField();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jTextField20 = new javax.swing.JTextField();
        jLabel62 = new javax.swing.JLabel();
        jTextField21 = new javax.swing.JTextField();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jPanel9 = new javax.swing.JPanel();
        jLabel63 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        Bg.setBackground(new java.awt.Color(242, 242, 242));
        Bg.setLayout(null);

        BerandaSideBar.setBackground(new java.awt.Color(242, 242, 242));
        BerandaSideBar.setMinimumSize(new java.awt.Dimension(1160, 768));
        BerandaSideBar.setPreferredSize(new java.awt.Dimension(1160, 768));
        BerandaSideBar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                BerandaSideBarMouseDragged(evt);
            }
        });
        BerandaSideBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BerandaSideBarMousePressed(evt);
            }
        });
        BerandaSideBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Menu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SI_AiraKost_Asset/menu.png"))); // NOI18N
        Menu1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Menu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Menu1MouseClicked(evt);
            }
        });
        BerandaSideBar.add(Menu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 34, 30));

        minimized2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SI_AiraKost_Asset/minimize.png"))); // NOI18N
        minimized2.setBorder(null);
        minimized2.setBorderPainted(false);
        minimized2.setContentAreaFilled(false);
        minimized2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimized2.setFocusPainted(false);
        minimized2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minimized2ActionPerformed(evt);
            }
        });
        BerandaSideBar.add(minimized2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 15, 20, 20));

        minimized3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SI_AiraKost_Asset/minimize1.png"))); // NOI18N
        minimized3.setBorder(null);
        minimized3.setBorderPainted(false);
        minimized3.setContentAreaFilled(false);
        minimized3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimized3.setFocusPainted(false);
        minimized3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minimized3ActionPerformed(evt);
            }
        });
        BerandaSideBar.add(minimized3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 10, 20, 20));

        close1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SI_AiraKost_Asset/close.png"))); // NOI18N
        close1.setBorder(null);
        close1.setBorderPainted(false);
        close1.setContentAreaFilled(false);
        close1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close1.setFocusPainted(false);
        close1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                close1ActionPerformed(evt);
            }
        });
        BerandaSideBar.add(close1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 10, -1, 20));

        judul1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SI_AiraKost_Asset/Label.png"))); // NOI18N
        BerandaSideBar.add(judul1, new org.netbeans.lib.awtextra.AbsoluteConstraints(445, 10, 260, 90));

        Slide1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SI_AiraKostFoto/1.png"))); // NOI18N
        BerandaSideBar.add(Slide1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, 450, 260));

        Text2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text2.setText("Jl. Taman Kampus, Lingkungan Krajan Timur, Tegalgede, Kec. Sumbersari, Kabupaten Jember");
        BerandaSideBar.add(Text2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 410, 570, 20));

        previous1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SI_AiraKost_Asset/icons8_back_26px.png"))); // NOI18N
        previous1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                previous1MousePressed(evt);
            }
        });
        BerandaSideBar.add(previous1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, 25, 25));

        next1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SI_AiraKost_Asset/icons8_forward_26px_2.png"))); // NOI18N
        next1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                next1MousePressed(evt);
            }
        });
        BerandaSideBar.add(next1, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 240, 25, 25));

        Kamar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SI_AiraKost_Asset/buttonKamar1.png"))); // NOI18N
        Kamar3.setPreferredSize(new java.awt.Dimension(190, 230));
        BerandaSideBar.add(Kamar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 500, 160, 200));

        CekButton3.setBorder(null);
        CekButton3.setBorderPainted(false);
        CekButton3.setContentAreaFilled(false);
        CekButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CekButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CekButton3ActionPerformed(evt);
            }
        });
        BerandaSideBar.add(CekButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 660, 61, 23));

        CekButton4.setBorder(null);
        CekButton4.setBorderPainted(false);
        CekButton4.setContentAreaFilled(false);
        CekButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CekButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CekButton4ActionPerformed(evt);
            }
        });
        BerandaSideBar.add(CekButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 660, 61, 23));

        Kamar4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SI_AiraKost_Asset/buttonKamar2.png"))); // NOI18N
        BerandaSideBar.add(Kamar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 500, 160, 200));

        Bg.add(BerandaSideBar);
        BerandaSideBar.setBounds(206, 0, 1160, 768);

        KamarSideBar.setBackground(new java.awt.Color(242, 242, 242));
        KamarSideBar.setMinimumSize(new java.awt.Dimension(1160, 768));
        KamarSideBar.setPreferredSize(new java.awt.Dimension(1160, 768));
        KamarSideBar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                KamarSideBarMouseDragged(evt);
            }
        });
        KamarSideBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                KamarSideBarMousePressed(evt);
            }
        });
        KamarSideBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Menu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SI_AiraKost_Asset/menu.png"))); // NOI18N
        Menu2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Menu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Menu2MouseClicked(evt);
            }
        });
        KamarSideBar.add(Menu2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 34, 30));

        minimized4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SI_AiraKost_Asset/minimize.png"))); // NOI18N
        minimized4.setBorder(null);
        minimized4.setBorderPainted(false);
        minimized4.setContentAreaFilled(false);
        minimized4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimized4.setFocusPainted(false);
        minimized4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minimized4ActionPerformed(evt);
            }
        });
        KamarSideBar.add(minimized4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 15, 20, 20));

        minimized5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SI_AiraKost_Asset/minimize1.png"))); // NOI18N
        minimized5.setBorder(null);
        minimized5.setBorderPainted(false);
        minimized5.setContentAreaFilled(false);
        minimized5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimized5.setFocusPainted(false);
        minimized5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minimized5ActionPerformed(evt);
            }
        });
        KamarSideBar.add(minimized5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 10, 20, 20));

        close2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SI_AiraKost_Asset/close.png"))); // NOI18N
        close2.setBorder(null);
        close2.setBorderPainted(false);
        close2.setContentAreaFilled(false);
        close2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close2.setFocusPainted(false);
        close2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                close2ActionPerformed(evt);
            }
        });
        KamarSideBar.add(close2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 10, -1, 20));

        judul2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SI_AiraKost_Asset/Label.png"))); // NOI18N
        KamarSideBar.add(judul2, new org.netbeans.lib.awtextra.AbsoluteConstraints(445, 10, 260, 90));

        CekButton5.setBorder(null);
        CekButton5.setBorderPainted(false);
        CekButton5.setContentAreaFilled(false);
        CekButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CekButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CekButton5ActionPerformed(evt);
            }
        });
        KamarSideBar.add(CekButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 660, 61, 23));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "*Kategori", "Kamar 1", "Kamar 2", " " }));
        jComboBox1.setBorder(null);
        jPanel3.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 210, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Kamar 1");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 380, -1, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Kamar 1");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 380, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Kamar 1");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 380, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Kamar 1");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 380, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Kamar 1");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 140, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Kamar 1");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 140, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Kamar 1");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Kamar 1");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, -1, -1));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SI_AiraKost_Asset/123.png"))); // NOI18N
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 120, 180, 240));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SI_AiraKost_Asset/123.png"))); // NOI18N
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 360, 180, 240));

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SI_AiraKost_Asset/123.png"))); // NOI18N
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, 180, 240));

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SI_AiraKost_Asset/123.png"))); // NOI18N
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 120, 180, 240));

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SI_AiraKost_Asset/123.png"))); // NOI18N
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 180, 240));

        jLabel20.setBackground(new java.awt.Color(255, 255, 255));
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SI_AiraKost_Asset/123.png"))); // NOI18N
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, 180, 240));

        jLabel21.setBackground(new java.awt.Color(255, 255, 255));
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SI_AiraKost_Asset/123.png"))); // NOI18N
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 360, 180, 240));

        jLabel22.setBackground(new java.awt.Color(255, 255, 255));
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SI_AiraKost_Asset/123.png"))); // NOI18N
        jPanel3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 360, 180, 240));

        KamarSideBar.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 1050, 610));

        Bg.add(KamarSideBar);
        KamarSideBar.setBounds(206, 0, 1160, 768);

        PemesananSideBar.setBackground(new java.awt.Color(242, 242, 242));
        PemesananSideBar.setMinimumSize(new java.awt.Dimension(1160, 768));
        PemesananSideBar.setPreferredSize(new java.awt.Dimension(1160, 768));
        PemesananSideBar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                PemesananSideBarMouseDragged(evt);
            }
        });
        PemesananSideBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PemesananSideBarMousePressed(evt);
            }
        });
        PemesananSideBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Menu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SI_AiraKost_Asset/menu.png"))); // NOI18N
        Menu5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Menu5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Menu5MouseClicked(evt);
            }
        });
        PemesananSideBar.add(Menu5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 34, 30));

        minimized8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SI_AiraKost_Asset/minimize.png"))); // NOI18N
        minimized8.setBorder(null);
        minimized8.setBorderPainted(false);
        minimized8.setContentAreaFilled(false);
        minimized8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimized8.setFocusPainted(false);
        minimized8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minimized8ActionPerformed(evt);
            }
        });
        PemesananSideBar.add(minimized8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 15, 20, 20));

        minimized9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SI_AiraKost_Asset/minimize1.png"))); // NOI18N
        minimized9.setBorder(null);
        minimized9.setBorderPainted(false);
        minimized9.setContentAreaFilled(false);
        minimized9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimized9.setFocusPainted(false);
        minimized9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minimized9ActionPerformed(evt);
            }
        });
        PemesananSideBar.add(minimized9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 10, 20, 20));

        close4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SI_AiraKost_Asset/close.png"))); // NOI18N
        close4.setBorder(null);
        close4.setBorderPainted(false);
        close4.setContentAreaFilled(false);
        close4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close4.setFocusPainted(false);
        close4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                close4ActionPerformed(evt);
            }
        });
        PemesananSideBar.add(close4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 10, -1, 20));

        judul4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SI_AiraKost_Asset/Label.png"))); // NOI18N
        PemesananSideBar.add(judul4, new org.netbeans.lib.awtextra.AbsoluteConstraints(445, 10, 260, 90));

        CekButton6.setBorder(null);
        CekButton6.setBorderPainted(false);
        CekButton6.setContentAreaFilled(false);
        CekButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CekButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CekButton6ActionPerformed(evt);
            }
        });
        PemesananSideBar.add(CekButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 660, 61, 23));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setOpaque(false);
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(96, 82, 76));
        jLabel5.setText("Formulir Pemesanan Kamar");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, -1, -1));

        ScrollData.setBackground(new java.awt.Color(255, 255, 255));
        ScrollData.setBorder(null);
        ScrollData.setOpaque(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Masuk.setBackground(new java.awt.Color(52, 135, 239));
        Masuk.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Masuk.setForeground(new java.awt.Color(255, 255, 255));
        Masuk.setText("Pesan");
        Masuk.setBorder(null);
        Masuk.setBorderPainted(false);
        Masuk.setContentAreaFilled(false);
        Masuk.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Masuk.setOpaque(true);
        Masuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MasukActionPerformed(evt);
            }
        });
        jPanel1.add(Masuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 670, 100, 40));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel6.setText("ID Booking");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 126, -1));

        jLabel39.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel39.setText("Tipe Kamar");
        jPanel1.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 126, -1));

        jTextField2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 335, -1));

        jTextField3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 335, -1));

        jLabel40.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel40.setText("Nama Lengkap");
        jPanel1.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 126, -1));

        jLabel41.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel41.setText("Lokasi Kamar");
        jPanel1.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 126, -1));

        jTextField4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 335, -1));

        jTextField5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jPanel1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 335, -1));

        jLabel42.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel42.setText("No. HP Pribadi");
        jPanel1.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 126, -1));

        jTextField7.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jPanel1.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, 335, -1));

        jLabel43.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel43.setText("Jenis Kelamin");
        jPanel1.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 126, -1));

        jTextField8.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jPanel1.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 335, -1));

        jLabel44.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel44.setText("Alamat");
        jPanel1.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 126, -1));

        jTextField9.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jPanel1.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 335, -1));

        jLabel45.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel45.setText("Total Bayar");
        jPanel1.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 580, 126, -1));

        jTextField10.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jPanel1.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 580, 335, -1));

        jLabel46.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel46.setText("Lama sewa");
        jPanel1.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, 126, -1));

        jLabel47.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel47.setText("Tanggal Masuk");
        jPanel1.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 126, -1));

        jLabel48.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel48.setText("No. HP Darurat");
        jPanel1.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 126, -1));

        jTextField13.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jPanel1.add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 380, 335, -1));

        jLabel49.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel49.setText("Kode Bayar");
        jPanel1.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 630, 126, -1));

        jTextField14.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jPanel1.add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 630, 335, -1));

        jRadioButton1.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setText("6 Bulan/disc.5%");
        jPanel1.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 540, 130, -1));

        jRadioButton2.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setText("Per-Bulan/normal");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 480, -1, -1));

        jRadioButton3.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton3.setText("3 bulan/normal");
        jPanel1.add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 510, 120, -1));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 60, 230, 280));
        jPanel1.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 430, 340, 30));

        ScrollData.setViewportView(jPanel1);

        jPanel5.add(ScrollData, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 1064, 480));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SI_AiraKost_Asset/Edge.png"))); // NOI18N
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 610));

        PemesananSideBar.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 1050, 610));

        Bg.add(PemesananSideBar);
        PemesananSideBar.setBounds(206, 0, 1160, 768);

        SideBarMenu.setBackground(new java.awt.Color(140, 120, 111));
        SideBarMenu.setMinimumSize(new java.awt.Dimension(210, 768));
        SideBarMenu.setPreferredSize(new java.awt.Dimension(210, 768));
        SideBarMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SI_AiraKost_Asset/profileW.png"))); // NOI18N
        SideBarMenu.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 30, 100, 100));

        jSeparator1.setBackground(new java.awt.Color(96, 82, 76));
        jSeparator1.setForeground(new java.awt.Color(96, 82, 76));
        SideBarMenu.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 188, 210, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Customer");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        SideBarMenu.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 140, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(179, 166, 165));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Menu");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        SideBarMenu.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        beranda.setBackground(new java.awt.Color(96, 82, 76));
        beranda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                berandaMouseClicked(evt);
            }
        });

        ico_beranda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SI_AiraKost_Asset/Icon_1_30px_P.png"))); // NOI18N

        Lbl_beranda.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        Lbl_beranda.setForeground(new java.awt.Color(255, 255, 255));
        Lbl_beranda.setText("Beranda");

        javax.swing.GroupLayout berandaLayout = new javax.swing.GroupLayout(beranda);
        beranda.setLayout(berandaLayout);
        berandaLayout.setHorizontalGroup(
            berandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(berandaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(ico_beranda, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Lbl_beranda, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );
        berandaLayout.setVerticalGroup(
            berandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, berandaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(berandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ico_beranda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Lbl_beranda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        SideBarMenu.add(beranda, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 205, 50));

        kamar.setBackground(new java.awt.Color(140, 120, 111));
        kamar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kamarMouseClicked(evt);
            }
        });

        ico_kamar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SI_AiraKost_Asset/icon_2_30px.png"))); // NOI18N

        Lbl_kamar.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        Lbl_kamar.setForeground(new java.awt.Color(207, 207, 207));
        Lbl_kamar.setText("Kamar");

        javax.swing.GroupLayout kamarLayout = new javax.swing.GroupLayout(kamar);
        kamar.setLayout(kamarLayout);
        kamarLayout.setHorizontalGroup(
            kamarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kamarLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(ico_kamar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Lbl_kamar, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        kamarLayout.setVerticalGroup(
            kamarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kamarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kamarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Lbl_kamar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(kamarLayout.createSequentialGroup()
                        .addComponent(ico_kamar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        SideBarMenu.add(kamar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 205, 50));

        pemesanan.setBackground(new java.awt.Color(140, 120, 111));
        pemesanan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pemesananMouseClicked(evt);
            }
        });

        ico_pemesanan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SI_AiraKost_Asset/icon_3_30px.png"))); // NOI18N

        Lbl_pemesanan.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        Lbl_pemesanan.setForeground(new java.awt.Color(207, 207, 207));
        Lbl_pemesanan.setText("Pemesanan");

        javax.swing.GroupLayout pemesananLayout = new javax.swing.GroupLayout(pemesanan);
        pemesanan.setLayout(pemesananLayout);
        pemesananLayout.setHorizontalGroup(
            pemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pemesananLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(ico_pemesanan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Lbl_pemesanan, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pemesananLayout.setVerticalGroup(
            pemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pemesananLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pemesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Lbl_pemesanan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pemesananLayout.createSequentialGroup()
                        .addComponent(ico_pemesanan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        SideBarMenu.add(pemesanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 205, 50));

        Logout.setBackground(new java.awt.Color(96, 82, 76));
        Logout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Logout.setForeground(new java.awt.Color(255, 255, 255));
        Logout.setText("Logout");
        Logout.setBorder(null);
        Logout.setBorderPainted(false);
        Logout.setContentAreaFilled(false);
        Logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Logout.setFocusPainted(false);
        Logout.setOpaque(true);
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });
        SideBarMenu.add(Logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 700, 100, 40));

        Bg.add(SideBarMenu);
        SideBarMenu.setBounds(0, 0, 210, 768);

        BerandaNoSidebar.setBackground(new java.awt.Color(242, 242, 242));
        BerandaNoSidebar.setMinimumSize(new java.awt.Dimension(1366, 768));
        BerandaNoSidebar.setPreferredSize(new java.awt.Dimension(1366, 768));
        BerandaNoSidebar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                BerandaNoSidebarMouseDragged(evt);
            }
        });
        BerandaNoSidebar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BerandaNoSidebarMousePressed(evt);
            }
        });
        BerandaNoSidebar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Menu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SI_AiraKost_Asset/menu.png"))); // NOI18N
        Menu3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Menu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Menu3MouseClicked(evt);
            }
        });
        BerandaNoSidebar.add(Menu3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 34, 30));

        minimized1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SI_AiraKost_Asset/minimize.png"))); // NOI18N
        minimized1.setBorder(null);
        minimized1.setBorderPainted(false);
        minimized1.setContentAreaFilled(false);
        minimized1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimized1.setFocusPainted(false);
        minimized1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minimized1ActionPerformed(evt);
            }
        });
        BerandaNoSidebar.add(minimized1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1256, 15, 20, 20));

        minimized.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SI_AiraKost_Asset/minimize1.png"))); // NOI18N
        minimized.setBorder(null);
        minimized.setBorderPainted(false);
        minimized.setContentAreaFilled(false);
        minimized.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimized.setFocusPainted(false);
        minimized.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minimizedActionPerformed(evt);
            }
        });
        BerandaNoSidebar.add(minimized, new org.netbeans.lib.awtextra.AbsoluteConstraints(1286, 10, 20, 20));

        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SI_AiraKost_Asset/close.png"))); // NOI18N
        close.setBorder(null);
        close.setBorderPainted(false);
        close.setContentAreaFilled(false);
        close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close.setFocusPainted(false);
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        BerandaNoSidebar.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(1316, 10, -1, 20));

        judul.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SI_AiraKost_Asset/Label.png"))); // NOI18N
        BerandaNoSidebar.add(judul, new org.netbeans.lib.awtextra.AbsoluteConstraints(545, 10, 260, 90));

        next.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SI_AiraKost_Asset/icons8_forward_26px_2.png"))); // NOI18N
        next.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                nextMousePressed(evt);
            }
        });
        BerandaNoSidebar.add(next, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 240, 25, 25));

        previous.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SI_AiraKost_Asset/icons8_back_26px.png"))); // NOI18N
        previous.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                previousMousePressed(evt);
            }
        });
        BerandaNoSidebar.add(previous, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 250, 25, 25));

        Slide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SI_AiraKostFoto/1.png"))); // NOI18N
        BerandaNoSidebar.add(Slide, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 130, 450, 260));

        Text1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text1.setText("Jl. Taman Kampus, Lingkungan Krajan Timur, Tegalgede, Kec. Sumbersari, Kabupaten Jember");
        BerandaNoSidebar.add(Text1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 410, 570, 20));

        CekButton2.setBorder(null);
        CekButton2.setBorderPainted(false);
        CekButton2.setContentAreaFilled(false);
        CekButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CekButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CekButton2ActionPerformed(evt);
            }
        });
        BerandaNoSidebar.add(CekButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 670, 61, 23));

        Kamar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SI_AiraKost_Asset/buttonKamar2.png"))); // NOI18N
        BerandaNoSidebar.add(Kamar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 500, 160, 200));

        CekButton1.setBorder(null);
        CekButton1.setBorderPainted(false);
        CekButton1.setContentAreaFilled(false);
        CekButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CekButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CekButton1ActionPerformed(evt);
            }
        });
        BerandaNoSidebar.add(CekButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 670, 61, 23));

        Kamar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SI_AiraKost_Asset/buttonKamar1.png"))); // NOI18N
        Kamar1.setPreferredSize(new java.awt.Dimension(190, 230));
        BerandaNoSidebar.add(Kamar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 500, 160, 200));

        Bg.add(BerandaNoSidebar);
        BerandaNoSidebar.setBounds(0, 0, 1366, 768);

        KamarNoSidebar.setBackground(new java.awt.Color(242, 242, 242));
        KamarNoSidebar.setMinimumSize(new java.awt.Dimension(1366, 768));
        KamarNoSidebar.setPreferredSize(new java.awt.Dimension(1366, 768));
        KamarNoSidebar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                KamarNoSidebarMouseDragged(evt);
            }
        });
        KamarNoSidebar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                KamarNoSidebarMousePressed(evt);
            }
        });
        KamarNoSidebar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Menu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SI_AiraKost_Asset/menu.png"))); // NOI18N
        Menu4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Menu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Menu4MouseClicked(evt);
            }
        });
        KamarNoSidebar.add(Menu4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 34, 30));

        minimized6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SI_AiraKost_Asset/minimize.png"))); // NOI18N
        minimized6.setBorder(null);
        minimized6.setBorderPainted(false);
        minimized6.setContentAreaFilled(false);
        minimized6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimized6.setFocusPainted(false);
        minimized6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minimized6ActionPerformed(evt);
            }
        });
        KamarNoSidebar.add(minimized6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1256, 15, 20, 20));

        minimized7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SI_AiraKost_Asset/minimize1.png"))); // NOI18N
        minimized7.setBorder(null);
        minimized7.setBorderPainted(false);
        minimized7.setContentAreaFilled(false);
        minimized7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimized7.setFocusPainted(false);
        minimized7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minimized7ActionPerformed(evt);
            }
        });
        KamarNoSidebar.add(minimized7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1286, 10, 20, 20));

        close3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SI_AiraKost_Asset/close.png"))); // NOI18N
        close3.setBorder(null);
        close3.setBorderPainted(false);
        close3.setContentAreaFilled(false);
        close3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close3.setFocusPainted(false);
        close3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                close3ActionPerformed(evt);
            }
        });
        KamarNoSidebar.add(close3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1316, 10, -1, 20));

        judul3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SI_AiraKost_Asset/Label.png"))); // NOI18N
        KamarNoSidebar.add(judul3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 10, 260, 90));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "*Kategori", "Kamar 1", "Kamar 2", " " }));
        jComboBox2.setBorder(null);
        jPanel4.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 210, -1));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Kamar 1");
        jPanel4.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 380, -1, -1));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Kamar 1");
        jPanel4.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 380, -1, -1));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Kamar 1");
        jPanel4.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 380, -1, -1));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Kamar 1");
        jPanel4.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 380, -1, -1));

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Kamar 1");
        jPanel4.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 140, -1, -1));

        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Kamar 1");
        jPanel4.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 140, -1, -1));

        jLabel29.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Kamar 1");
        jPanel4.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, -1, -1));

        jLabel30.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Kamar 1");
        jPanel4.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, -1, -1));

        jLabel31.setBackground(new java.awt.Color(255, 255, 255));
        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SI_AiraKost_Asset/123.png"))); // NOI18N
        jPanel4.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 120, 180, 240));

        jLabel32.setBackground(new java.awt.Color(255, 255, 255));
        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SI_AiraKost_Asset/123.png"))); // NOI18N
        jPanel4.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 360, 180, 240));

        jLabel33.setBackground(new java.awt.Color(255, 255, 255));
        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SI_AiraKost_Asset/123.png"))); // NOI18N
        jPanel4.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, 180, 240));

        jLabel34.setBackground(new java.awt.Color(255, 255, 255));
        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SI_AiraKost_Asset/123.png"))); // NOI18N
        jPanel4.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 120, 180, 240));

        jLabel35.setBackground(new java.awt.Color(255, 255, 255));
        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SI_AiraKost_Asset/123.png"))); // NOI18N
        jPanel4.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 180, 240));

        jLabel36.setBackground(new java.awt.Color(255, 255, 255));
        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SI_AiraKost_Asset/123.png"))); // NOI18N
        jPanel4.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, 180, 240));

        jLabel37.setBackground(new java.awt.Color(255, 255, 255));
        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SI_AiraKost_Asset/123.png"))); // NOI18N
        jPanel4.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 360, 180, 240));

        jLabel38.setBackground(new java.awt.Color(255, 255, 255));
        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SI_AiraKost_Asset/123.png"))); // NOI18N
        jPanel4.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 360, 180, 240));

        KamarNoSidebar.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 1050, 610));

        Bg.add(KamarNoSidebar);
        KamarNoSidebar.setBounds(0, 0, 1366, 768);

        PemesananNoSidebar.setBackground(new java.awt.Color(242, 242, 242));
        PemesananNoSidebar.setMinimumSize(new java.awt.Dimension(1366, 768));
        PemesananNoSidebar.setPreferredSize(new java.awt.Dimension(1366, 768));
        PemesananNoSidebar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                PemesananNoSidebarMouseDragged(evt);
            }
        });
        PemesananNoSidebar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PemesananNoSidebarMousePressed(evt);
            }
        });
        PemesananNoSidebar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Menu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SI_AiraKost_Asset/menu.png"))); // NOI18N
        Menu6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Menu6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Menu6MouseClicked(evt);
            }
        });
        PemesananNoSidebar.add(Menu6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 34, 30));

        minimized10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SI_AiraKost_Asset/minimize.png"))); // NOI18N
        minimized10.setBorder(null);
        minimized10.setBorderPainted(false);
        minimized10.setContentAreaFilled(false);
        minimized10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimized10.setFocusPainted(false);
        minimized10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minimized10ActionPerformed(evt);
            }
        });
        PemesananNoSidebar.add(minimized10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1256, 15, 20, 20));

        minimized11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SI_AiraKost_Asset/minimize1.png"))); // NOI18N
        minimized11.setBorder(null);
        minimized11.setBorderPainted(false);
        minimized11.setContentAreaFilled(false);
        minimized11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimized11.setFocusPainted(false);
        minimized11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minimized11ActionPerformed(evt);
            }
        });
        PemesananNoSidebar.add(minimized11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1286, 10, 20, 20));

        close5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SI_AiraKost_Asset/close.png"))); // NOI18N
        close5.setBorder(null);
        close5.setBorderPainted(false);
        close5.setContentAreaFilled(false);
        close5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close5.setFocusPainted(false);
        close5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                close5ActionPerformed(evt);
            }
        });
        PemesananNoSidebar.add(close5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1316, 10, -1, 20));

        judul5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SI_AiraKost_Asset/Label.png"))); // NOI18N
        PemesananNoSidebar.add(judul5, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 10, 260, 90));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setOpaque(false);
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel50.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(96, 82, 76));
        jLabel50.setText("Formulir Pemesanan Kamar");
        jPanel7.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, -1, -1));

        ScrollData1.setBackground(new java.awt.Color(255, 255, 255));
        ScrollData1.setBorder(null);
        ScrollData1.setOpaque(false);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Masuk1.setBackground(new java.awt.Color(52, 135, 239));
        Masuk1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Masuk1.setForeground(new java.awt.Color(255, 255, 255));
        Masuk1.setText("Pesan");
        Masuk1.setBorder(null);
        Masuk1.setBorderPainted(false);
        Masuk1.setContentAreaFilled(false);
        Masuk1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Masuk1.setOpaque(true);
        Masuk1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Masuk1ActionPerformed(evt);
            }
        });
        jPanel8.add(Masuk1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 670, 100, 40));

        jLabel51.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel51.setText("ID Booking");
        jPanel8.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 126, -1));

        jLabel52.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel52.setText("Tipe Kamar");
        jPanel8.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 126, -1));

        jTextField6.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jPanel8.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 335, -1));

        jTextField11.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jPanel8.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 335, -1));

        jLabel53.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel53.setText("Nama Lengkap");
        jPanel8.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 126, -1));

        jLabel54.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel54.setText("Lokasi Kamar");
        jPanel8.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 126, -1));

        jTextField12.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jPanel8.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 335, -1));

        jTextField15.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jPanel8.add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 335, -1));

        jLabel55.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel55.setText("No. HP Pribadi");
        jPanel8.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 126, -1));

        jTextField16.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jPanel8.add(jTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, 335, -1));

        jLabel56.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel56.setText("Jenis Kelamin");
        jPanel8.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 126, -1));

        jTextField17.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jPanel8.add(jTextField17, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 335, -1));

        jLabel57.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel57.setText("Alamat");
        jPanel8.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 126, -1));

        jTextField18.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jPanel8.add(jTextField18, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 335, -1));

        jLabel58.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel58.setText("Total Bayar");
        jPanel8.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 580, 126, -1));

        jTextField19.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jPanel8.add(jTextField19, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 580, 335, -1));

        jLabel59.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel59.setText("Lama sewa");
        jPanel8.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, 126, -1));

        jLabel60.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel60.setText("Tanggal Masuk");
        jPanel8.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 126, -1));

        jLabel61.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel61.setText("No. HP Darurat");
        jPanel8.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 126, -1));

        jTextField20.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jPanel8.add(jTextField20, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 380, 335, -1));

        jLabel62.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel62.setText("Kode Bayar");
        jPanel8.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 630, 126, -1));

        jTextField21.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jPanel8.add(jTextField21, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 630, 335, -1));

        jRadioButton4.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton4.setText("6 Bulan/disc.5%");
        jPanel8.add(jRadioButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 540, 130, -1));

        jRadioButton5.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton5.setText("Per-Bulan/normal");
        jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton5ActionPerformed(evt);
            }
        });
        jPanel8.add(jRadioButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 480, -1, -1));

        jRadioButton6.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton6.setText("3 bulan/normal");
        jPanel8.add(jRadioButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 510, 120, -1));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );

        jPanel8.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 60, 230, 280));

        ScrollData1.setViewportView(jPanel8);

        jPanel7.add(ScrollData1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 1064, 480));

        jLabel63.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SI_AiraKost_Asset/Edge.png"))); // NOI18N
        jPanel7.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 610));

        PemesananNoSidebar.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 110, 1050, 610));

        Bg.add(PemesananNoSidebar);
        PemesananNoSidebar.setBounds(0, 0, 1366, 768);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Bg, javax.swing.GroupLayout.DEFAULT_SIZE, 1366, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Bg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1366, 768));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void kamarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kamarMouseClicked
        ImageIcon kmr = new ImageIcon(getClass().getResource("/SI_AiraKost_Asset/icon_2_30px_P.png"));
        ico_kamar.setIcon(kmr);
        ImageIcon brd = new ImageIcon(getClass().getResource("/SI_AiraKost_Asset/icon_1_30px.png"));
        ico_beranda.setIcon(brd);
        ImageIcon psn = new ImageIcon(getClass().getResource("/SI_AiraKost_Asset/icon_3_30px.png"));
        ico_pemesanan.setIcon(psn);
        setColor(kamar);
        setColorText(Lbl_kamar);
        resetColor(beranda);
        resetColorText(Lbl_beranda);
        resetColor(pemesanan);
        resetColorText(Lbl_pemesanan);

        KamarSideBar.setVisible(true);
        KamarSideBar.setEnabled(true);
        BerandaSideBar.setVisible(false);
        BerandaSideBar.setEnabled(false);
        PemesananSideBar.setVisible(false);
        PemesananSideBar.setEnabled(false);
    }//GEN-LAST:event_kamarMouseClicked

    private void berandaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_berandaMouseClicked
        ImageIcon brd = new ImageIcon(getClass().getResource("/SI_AiraKost_Asset/icon_1_30px_P.png"));
        ico_beranda.setIcon(brd);
        ImageIcon kmr = new ImageIcon(getClass().getResource("/SI_AiraKost_Asset/icon_2_30px.png"));
        ico_kamar.setIcon(kmr);
        ImageIcon psn = new ImageIcon(getClass().getResource("/SI_AiraKost_Asset/icon_3_30px.png"));
        ico_pemesanan.setIcon(psn);
        setColor(beranda);
        setColorText(Lbl_beranda);
        resetColor(kamar);
        resetColorText(Lbl_kamar);
        resetColor(pemesanan);
        resetColorText(Lbl_pemesanan);

        BerandaSideBar.setVisible(true);
        BerandaSideBar.setEnabled(true);
        KamarSideBar.setVisible(false);
        KamarSideBar.setEnabled(false);
        PemesananSideBar.setVisible(false);
        PemesananSideBar.setEnabled(false);
    }//GEN-LAST:event_berandaMouseClicked

    private void KamarNoSidebarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KamarNoSidebarMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_KamarNoSidebarMousePressed

    private void KamarNoSidebarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KamarNoSidebarMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_KamarNoSidebarMouseDragged

    private void close3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_close3ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_close3ActionPerformed

    private void minimized7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minimized7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_minimized7ActionPerformed

    private void minimized6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minimized6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_minimized6ActionPerformed

    private void BerandaNoSidebarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BerandaNoSidebarMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_BerandaNoSidebarMousePressed

    private void BerandaNoSidebarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BerandaNoSidebarMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_BerandaNoSidebarMouseDragged

    private void CekButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CekButton1ActionPerformed

    }//GEN-LAST:event_CekButton1ActionPerformed

    private void CekButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CekButton2ActionPerformed

    }//GEN-LAST:event_CekButton2ActionPerformed

    private void previousMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_previousMousePressed

    }//GEN-LAST:event_previousMousePressed

    private void nextMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextMousePressed

    }//GEN-LAST:event_nextMousePressed

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        System.exit(0);
    }//GEN-LAST:event_closeActionPerformed

    private void minimizedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minimizedActionPerformed
        new java.util.Timer().schedule(new TimerTask() {
            @Override
            public void run() {
                LoginMini mini = new LoginMini();
                mini.show();
                dispose();
            }
        }, 5 * 5);
    }//GEN-LAST:event_minimizedActionPerformed

    private void minimized1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minimized1ActionPerformed
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minimized1ActionPerformed

    private void KamarSideBarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KamarSideBarMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_KamarSideBarMousePressed

    private void KamarSideBarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KamarSideBarMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_KamarSideBarMouseDragged

    private void CekButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CekButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CekButton5ActionPerformed

    private void close2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_close2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_close2ActionPerformed

    private void minimized5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minimized5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_minimized5ActionPerformed

    private void minimized4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minimized4ActionPerformed
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minimized4ActionPerformed

    private void BerandaSideBarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BerandaSideBarMousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_BerandaSideBarMousePressed

    private void BerandaSideBarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BerandaSideBarMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_BerandaSideBarMouseDragged

    private void CekButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CekButton4ActionPerformed

    }//GEN-LAST:event_CekButton4ActionPerformed

    private void CekButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CekButton3ActionPerformed

    }//GEN-LAST:event_CekButton3ActionPerformed

    private void next1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_next1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_next1MousePressed

    private void previous1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_previous1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_previous1MousePressed

    private void close1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_close1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_close1ActionPerformed

    private void minimized3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minimized3ActionPerformed
        //        new java.util.Timer().schedule(new TimerTask() {
        //            @Override
        //            public void run() {
        //                LoginMini mini = new LoginMini();
        //                mini.show();
        //                dispose();
        //            }
        //        }, 5 * 5);
    }//GEN-LAST:event_minimized3ActionPerformed

    private void minimized2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minimized2ActionPerformed
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minimized2ActionPerformed

    private void pemesananMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pemesananMouseClicked
        ImageIcon psn = new ImageIcon(getClass().getResource("/SI_AiraKost_Asset/icon_3_30px_P.png"));
        ico_pemesanan.setIcon(psn);
        ImageIcon brd = new ImageIcon(getClass().getResource("/SI_AiraKost_Asset/icon_1_30px.png"));
        ico_beranda.setIcon(brd);
        ImageIcon kmr = new ImageIcon(getClass().getResource("/SI_AiraKost_Asset/icon_2_30px.png"));
        ico_kamar.setIcon(kmr);

        setColor(pemesanan);
        setColorText(Lbl_pemesanan);
        resetColor(beranda);
        resetColorText(Lbl_beranda);
        resetColor(kamar);
        resetColorText(Lbl_kamar);

        PemesananSideBar.setVisible(true);
        PemesananSideBar.setEnabled(true);
        BerandaSideBar.setVisible(false);
        BerandaSideBar.setEnabled(false);
        KamarSideBar.setVisible(false);
        KamarSideBar.setEnabled(false);
    }//GEN-LAST:event_pemesananMouseClicked

    private void Menu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu1MouseClicked
        SideBarMenu.setVisible(false);
        SideBarMenu.setEnabled(false);
        BerandaSideBar.setVisible(false);
        BerandaSideBar.setEnabled(false);
        KamarSideBar.setVisible(false);
        KamarSideBar.setEnabled(false);
        PemesananSideBar.setVisible(false);
        PemesananSideBar.setEnabled(false);

        BerandaNoSidebar.setVisible(true);
        BerandaNoSidebar.setEnabled(true);

    }//GEN-LAST:event_Menu1MouseClicked

    private void Menu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu3MouseClicked
        SideBarMenu.setVisible(true);
        SideBarMenu.setEnabled(true);
        BerandaSideBar.setVisible(true);
        BerandaSideBar.setEnabled(true);

        BerandaNoSidebar.setVisible(false);
        BerandaNoSidebar.setEnabled(false);
    }//GEN-LAST:event_Menu3MouseClicked

    private void Menu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu2MouseClicked
        SideBarMenu.setVisible(false);
        SideBarMenu.setEnabled(false);
        BerandaSideBar.setVisible(false);
        BerandaSideBar.setEnabled(false);
        KamarSideBar.setVisible(false);
        KamarSideBar.setEnabled(false);
        PemesananSideBar.setVisible(false);
        PemesananSideBar.setEnabled(false);

        KamarNoSidebar.setVisible(true);
        KamarNoSidebar.setEnabled(true);
    }//GEN-LAST:event_Menu2MouseClicked

    private void Menu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu4MouseClicked
        SideBarMenu.setVisible(true);
        SideBarMenu.setEnabled(true);
        KamarSideBar.setVisible(true);
        KamarSideBar.setEnabled(true);

        KamarNoSidebar.setVisible(false);
        KamarNoSidebar.setEnabled(false);

    }//GEN-LAST:event_Menu4MouseClicked

    private void Menu5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu5MouseClicked
        SideBarMenu.setVisible(false);
        SideBarMenu.setEnabled(false);
        PemesananSideBar.setVisible(false);
        PemesananSideBar.setEnabled(false);
        BerandaSideBar.setVisible(false);
        BerandaSideBar.setEnabled(false);
        KamarSideBar.setVisible(false);
        KamarSideBar.setEnabled(false);

        PemesananNoSidebar.setVisible(true);
        PemesananNoSidebar.setEnabled(true);
    }//GEN-LAST:event_Menu5MouseClicked

    private void minimized8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minimized8ActionPerformed
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minimized8ActionPerformed

    private void minimized9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minimized9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_minimized9ActionPerformed

    private void close4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_close4ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_close4ActionPerformed

    private void CekButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CekButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CekButton6ActionPerformed

    private void PemesananSideBarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PemesananSideBarMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_PemesananSideBarMouseDragged

    private void PemesananSideBarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PemesananSideBarMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_PemesananSideBarMousePressed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void MasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MasukActionPerformed
        //        Beranda f3 = new Beranda();
        //        f3.setVisible(true);
        //new Beranda().show();
        this.setVisible(false);
    }//GEN-LAST:event_MasukActionPerformed

    private void Menu6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu6MouseClicked
        SideBarMenu.setVisible(true);
        SideBarMenu.setEnabled(true);
        PemesananSideBar.setVisible(true);
        PemesananSideBar.setEnabled(true);

        PemesananNoSidebar.setVisible(false);
        PemesananNoSidebar.setEnabled(false);
    }//GEN-LAST:event_Menu6MouseClicked

    private void minimized10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minimized10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_minimized10ActionPerformed

    private void minimized11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minimized11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_minimized11ActionPerformed

    private void close5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_close5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_close5ActionPerformed

    private void PemesananNoSidebarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PemesananNoSidebarMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_PemesananNoSidebarMouseDragged

    private void PemesananNoSidebarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PemesananNoSidebarMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_PemesananNoSidebarMousePressed

    private void Masuk1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Masuk1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Masuk1ActionPerformed

    private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton5ActionPerformed

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        new java.util.Timer().schedule(new TimerTask() {
            @Override
            public void run() {
                Login lg = new Login();
                lg.show();
                dispose();
            }
        }, 5 * 5);
    }//GEN-LAST:event_LogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BerandaNoSidebar;
    private javax.swing.JPanel BerandaSideBar;
    private javax.swing.JPanel Bg;
    private javax.swing.JButton CekButton1;
    private javax.swing.JButton CekButton2;
    private javax.swing.JButton CekButton3;
    private javax.swing.JButton CekButton4;
    private javax.swing.JButton CekButton5;
    private javax.swing.JButton CekButton6;
    private javax.swing.JLabel Kamar1;
    private javax.swing.JLabel Kamar2;
    private javax.swing.JLabel Kamar3;
    private javax.swing.JLabel Kamar4;
    private javax.swing.JPanel KamarNoSidebar;
    private javax.swing.JPanel KamarSideBar;
    private javax.swing.JLabel Lbl_beranda;
    private javax.swing.JLabel Lbl_kamar;
    private javax.swing.JLabel Lbl_pemesanan;
    private javax.swing.JToggleButton Logout;
    private javax.swing.JToggleButton Masuk;
    private javax.swing.JToggleButton Masuk1;
    private javax.swing.JLabel Menu1;
    private javax.swing.JLabel Menu2;
    private javax.swing.JLabel Menu3;
    private javax.swing.JLabel Menu4;
    private javax.swing.JLabel Menu5;
    private javax.swing.JLabel Menu6;
    private javax.swing.JPanel PemesananNoSidebar;
    private javax.swing.JPanel PemesananSideBar;
    private javax.swing.JScrollPane ScrollData;
    private javax.swing.JScrollPane ScrollData1;
    private javax.swing.JPanel SideBarMenu;
    private javax.swing.JLabel Slide;
    private javax.swing.JLabel Slide1;
    private javax.swing.JLabel Text1;
    private javax.swing.JLabel Text2;
    private javax.swing.JPanel beranda;
    private javax.swing.JButton close;
    private javax.swing.JButton close1;
    private javax.swing.JButton close2;
    private javax.swing.JButton close3;
    private javax.swing.JButton close4;
    private javax.swing.JButton close5;
    private javax.swing.JLabel ico_beranda;
    private javax.swing.JLabel ico_kamar;
    private javax.swing.JLabel ico_pemesanan;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JLabel judul;
    private javax.swing.JLabel judul1;
    private javax.swing.JLabel judul2;
    private javax.swing.JLabel judul3;
    private javax.swing.JLabel judul4;
    private javax.swing.JLabel judul5;
    private javax.swing.JPanel kamar;
    private javax.swing.JButton minimized;
    private javax.swing.JButton minimized1;
    private javax.swing.JButton minimized10;
    private javax.swing.JButton minimized11;
    private javax.swing.JButton minimized2;
    private javax.swing.JButton minimized3;
    private javax.swing.JButton minimized4;
    private javax.swing.JButton minimized5;
    private javax.swing.JButton minimized6;
    private javax.swing.JButton minimized7;
    private javax.swing.JButton minimized8;
    private javax.swing.JButton minimized9;
    private javax.swing.JLabel next;
    private javax.swing.JLabel next1;
    private javax.swing.JPanel pemesanan;
    private javax.swing.JLabel previous;
    private javax.swing.JLabel previous1;
    // End of variables declaration//GEN-END:variables
}
